### ISSUE TITLE
Fix the README.md and add instructions on how to train a dialog

### ISSUE THREAD

**Issue by germanattanasio** [watson-developer-cloud/dialog-nodejs#1]
We currently don't have instructions on how to create a dialog so when people fork and deploy this demo it simple doesn't work for them.

@tparikh reported this.

**Comment by germanattanasio** [comment]
@mitchmason can you take a look at this problem?

**Comment by mitchmason** [comment]
the doc site is here... ive included in an email to every person we've added
https://dialog-doc-la.mybluemix.net/doc/dialog/index.html

once we go open beta it will be visible via bluemix
