### ISSUE TITLE
xml regular expression not working

### ISSUE THREAD

**Issue by pulsarviki** [watson-developer-cloud/dialog-nodejs#35]
I tried to add a regular expression to the xml tag but it doesn't seem to work properly. I've added the following line

                                                    <input>
                                                        <grammar>
                                                            <item>!([a-zA-Z]{3,30}\s*)+ </item>
                                                        </grammar>
                                                        <output>
                                                            <prompt selectionType="RANDOM">
                                                                <item>severity:</item>
                                                            </prompt>
                                                        </output>
                                                    </input>

**Comment by mitchmason** [comment]
Unfortunately when using regex within Dialog, there is no real way to validate whether your regex is correct. Do you have a tool to test that?

There should be a space in between the exclamation and the actual function, maybe that is causing the error.

What type of inputs are you trying to match to? Maybe I can try to help you write something.
